In [1]:
import torch

In [31]:
a = torch.tensor([[1,2,3,4,5,6,7,8], [9,10,11,12,13,14,15,16]])
a

tensor([[  1,   2,   3,   4,   5,   6,   7,   8],
        [  9,  10,  11,  12,  13,  14,  15,  16]])

In [3]:
b = torch.tensor([
    [[10,2,3,4,5,6,7,8], [11,2,3,4,5,6,7,8], [12,2,3,4,5,6,7,8]],
    [[90,10,11,12,13,14,15,16], [91,10,11,12,13,14,15,16], [92,10,11,12,13,14,15,16]]
])
b

tensor([[[ 10,   2,   3,   4,   5,   6,   7,   8],
         [ 11,   2,   3,   4,   5,   6,   7,   8],
         [ 12,   2,   3,   4,   5,   6,   7,   8]],

        [[ 90,  10,  11,  12,  13,  14,  15,  16],
         [ 91,  10,  11,  12,  13,  14,  15,  16],
         [ 92,  10,  11,  12,  13,  14,  15,  16]]])

In [4]:
torch.cat((a.view(b.size(0), 1, -1), b), dim=1)

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8],
         [ 10,   2,   3,   4,   5,   6,   7,   8],
         [ 11,   2,   3,   4,   5,   6,   7,   8],
         [ 12,   2,   3,   4,   5,   6,   7,   8]],

        [[  9,  10,  11,  12,  13,  14,  15,  16],
         [ 90,  10,  11,  12,  13,  14,  15,  16],
         [ 91,  10,  11,  12,  13,  14,  15,  16],
         [ 92,  10,  11,  12,  13,  14,  15,  16]]])

In [25]:
c = torch.range(0, 63, dtype=torch.int).reshape(2, -1, 8)
c

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [  8,   9,  10,  11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29,  30,  31]],

        [[ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]]], dtype=torch.int32)

In [34]:
a = a.view(1, -1, 8)
a

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8],
         [  9,  10,  11,  12,  13,  14,  15,  16]]])

In [29]:
c.permute(1,0,2)[:-1]

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7],
         [ 32,  33,  34,  35,  36,  37,  38,  39]],

        [[  8,   9,  10,  11,  12,  13,  14,  15],
         [ 40,  41,  42,  43,  44,  45,  46,  47]],

        [[ 16,  17,  18,  19,  20,  21,  22,  23],
         [ 48,  49,  50,  51,  52,  53,  54,  55]]], dtype=torch.int32)